server:
  port: 8080

spring:
  application:
    name: eleven-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


management.endpoint.gateway.enabled: true
management.endpoints.web.exposure.include: gateway

