version: '3'

services:
#  nacos:
#    image: nacos/nacos-server:v2.2.3-slim
#    container_name: nacos-standalone-mysql
#    environment:
#      - PREFER_HOST_MODE=hostname
#      - MODE=standalone
#      - SPRING_DATASOURCE_PLATFORM=mysql
#      - MYSQL_SERVICE_HOST=mysql
#      - MYSQL_SERVICE_DB_NAME=nacos
#      - MYSQL_SERVICE_PORT=3306
#      - MYSQL_SERVICE_USER=root
#      - MYSQL_SERVICE_PASSWORD=daohaosima2A
#      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
#      - NACOS_AUTH_IDENTITY_KEY=2222
#      - NACOS_AUTH_IDENTITY_VALUE=2xxx
#      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
#    network_mode: host
#    restart: always

  mysql:
    container_name: mysql
    image: mysql:8
#    env_file:
#      - ../env/mysql.env
    volumes:
      - eleven-data-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10


  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - eleven-data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example

  mongo:
    image: mongo
    restart: always
    volumes:
      - eleven-data-mongo:/var/lib/backup/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  eleven-data-postgres:
  eleven-data-redis:
  eleven-data-mongo:
  eleven-data-mysql:
