version: '3'

services:
#  nacos:
#    image: nacos/nacos-server:v2.2.3-slim
#    container_name: nacos-standalone-mysql
#    environment:
#      - PREFER_HOST_MODE=hostname
#      - MODE=standalone
#      - SPRING_DATASOURCE_PLATFORM=mysql
#      - MYSQL_SERVICE_HOST=mysql
#      - MYSQL_SERVICE_DB_NAME=nacos
#      - MYSQL_SERVICE_PORT=3306
#      - MYSQL_SERVICE_USER=root
#      - MYSQL_SERVICE_PASSWORD=daohaosima2A
#      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
#      - NACOS_AUTH_IDENTITY_KEY=2222
#      - NACOS_AUTH_IDENTITY_VALUE=2xxx
#      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
#    network_mode: host
#    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: admin_vhost
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 111111
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ${DATA_STORAGE}/rabbitmq:/var/lib/rabbitmq

  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - ${DATA_STORAGE}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_RANDOM_ROOT_PASSWORD: no
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10


  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ${DATA_STORAGE}/postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 111111

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_STORAGE}/mongodb/db:/data/db
      - ${DATA_STORAGE}/mongodb/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:6
    ports:
      - "6379:6379"
