name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: maven:3.8.5-openjdk-17
    steps:
      - run: mvn clean package -DskipTests=true
