server:
  port: 8080

spring:
  application:
    name: eleven-gateway

  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
        - PreserveHostHeader
      routes:
        #  UPMS 用户权限管理
        - id: upms
          uri: lb://eleven-upms
          predicates:
            - Path=/api/users/**,/
