server:
  port: 8080

spring:
  application:
    name: eleven-gateway

  cloud:
    gateway:
      routes:
        #  API 服务
        - uri: lb://upms
          predicates:
            - Path=/users/**
