server:
  port: 8000

spring:
  application:
    name: eleven-app-demo

demcia:
  eleven:
    open-api:
      title: 德玛西亚
      version: 1.0.0.dev
      terms-of-service: https://www.demcia.com/
      contact:
        email: demcia@demcia.com
        name: 德玛西亚小分队
        url: https://www.demcia.com/
      license:
        name: Apache 2.0
        url: https://www.demcia.com/