server:
  port: 8000

spring:
  application:
    name: eleven-api

eleven:
  security:
    auth-mode: remote
  restful:
    prefix: /api
  open-api:
    title: 开放 API 服务
    description: 这是一个伟大而又了不起的工程！
    version: 1.0.0.dev
    terms-of-service: https://www.demcia.com/
    contact:
      email: demcia@demcia.com
      name: 德玛西亚小分队
      url: https://www.demcia.com/
    license:
      name: Apache 2.0
      url: https://www.demcia.com/
  domain:
    identity:
      id-type: snowflake

logging:
  level:
    sql: info
    web: info
    root: info


