@startuml
left to right direction

actor HotelStaff as staff
actor SystemAdmin as admin

rectangle Register {
  usecase "register hotel" as register
  usecase "review register" as review
}

rectangle Hotel {
  usecase "update hotel" as update
  usecase "review register" as review
}

admin --> review
staff --> register
staff --> update

@enduml
