server:
  port: 9001

spring:
  application:
    name: gateway
  datasource:
    url: ${db.gateway.url}
    username: ${db.gateway.username}
    password: ${db.gateway.password}

eleven:
  cache:
    duration: PT8H
    serializer: jackson

  open-api:
    title: API 网关
    description: 这是一个伟大而又了不起的工程！
    version: 1.0.0.dev
    terms-of-service: https://www.demcia.com/
    contact:
      email: demcia@demcia.com
      name: 德玛西亚小分队
      url: https://www.demcia.com/
    license:
      name: Apache 2.0
      url: https://www.demcia.com/


