server:
  port: 8000

spring:
  application:
    name: eleven-api
  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: ${db.upms.url}
          username: ${db.upms.username}
          password: ${db.upms.password}
          hikari:
            max-lifetime: ${db.upms.maxLifetime:30000}
            max-pool-size: ${db.upms.maxSize:5}

eleven:
  restful:
    prefix: /api
  open-api:
    title: 开放 API 服务
    description: 这是一个伟大而又了不起的工程！
    version: 1.0.0.dev
    terms-of-service: https://www.demcia.com/
    contact:
      email: demcia@demcia.com
      name: 德玛西亚小分队
      url: https://www.demcia.com/
    license:
      name: Apache 2.0
      url: https://www.demcia.com/


logging:
  level:
    sql: info
    web: info
    root: info
    'com.demcia': debug
    'sleuth.sql': debug


