server:
  port: 9000
  error:
    include-message: always

spring:
  application:
    name: eleven-upms

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eleven_upms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: eleven
    password: eleven

  jpa:
    generate-ddl: true

eleven:
  rest:
    prefix: /api
  open-api:
    title: 用户授权管理
    description: 这是一个伟大而又了不起的工程！
    version: 1.0.0.dev
    terms-of-service: https://www.demcia.com/
    contact:
      email: demcia@demcia.com
      name: 德玛西亚小分队
      url: https://www.demcia.com/
    license:
      name: Apache 2.0
      url: https://www.demcia.com/
