server:
  port: 9000


spring:
  application:
    name: eleven-upms
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: ${db.upms.url}
          username: ${db.upms.username}
          password: ${db.upms.password}
          hikari:
            max-lifetime: ${db.upms.maxLifetime:30000}
            max-pool-size: ${db.upms.maxSize:5}
  data:
    mongodb:
      host: 192.168.2.250
      username: eleven
      password: eleven
      port: 27017
      database: eleven

eleven:
  upms:
    default-password: 123456
  security:
    auth-mode: local
  open-api:
    title: 用户授权管理
    description: 这是一个伟大而又了不起的工程！
    version: 1.0.0.dev
    terms-of-service: https://www.demcia.com/
    contact:
      email: demcia@demcia.com
      name: 德玛西亚小分队
      url: https://www.demcia.com/
    license:
      name: Apache 2.0
      url: https://www.demcia.com/

logging:
  level:
    jdbc: debug


